import type { Metadata } from "next";
import { Actor } from "next/font/google";
import "./globals.css";

const actor = Actor({
  variable: "--font-actor",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={actor.variable}>{children}</body>
    </html>
  );
}
